version: '3'

services:
  mi-mongo:
    image: mongo
    container_name: mi-mongo
    networks:
      mi-red:
        ipv4_address: 172.24.0.10
    volumes:
      - mi-volumen:/data/db
    ports:
      - "27017:27017"
    restart: always

  mi-mongo-express:
    image: mongo-express
    container_name: mi-mongo-express
    depends_on:
      -mi-mongo
    networks:
      mi-red:
        ipv4_address: 172.24.0.11
    environment:
      - ME_CONFIG_MONGODB_SERVER=mi-mongo
    ports:
      - "8081:8081"
    restart: always

networks:
  mi-red:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

volumes:
  mi-volumen:





